### ISSUE TITLE
找不到客户端启动ssl认证的配置

### ISSUE THREAD

**Issue by Roan123** [Hakky54/mutual-tls-ssl#100]
为了让客户端知晓信任库的存在，您还需要告知其信任库的正确位置、密码、以及身份验证已启用。您可以在客户端的application.yml文件中，提供如下属性：

client: 

  ssl: 

    one-way-authentication-enabled: true 

    two-way-authentication-enabled: false 

    trust-store: truststore.jks 

    trust-store-password: secret 

看你的文章不是配这个配置就可以了嘛？好像找不到在哪里？

reference:
https://mp.weixin.qq.com/s/i_hU2GXysSGA9JWAbcxoOA

**Comment by Hakky54** [comment]
It is located here: https://github.com/Hakky54/mutual-tls-ssl/blob/master/client/src/test/resources/application.yml
In the application test resources. You can adjust that and rerun the client and it should work. Can you please try it out on your side and share the results?

**Comment by Roan123** [comment]
I guess they are project-defined configuration instead of providing by Spring or other frameworks I used, so I'm not using them any more. After I failed trying to use openssl since openssl and pkcs#12 are more common in use compared to keytool and jks, I implement two-way ssl of my version refer to your article. It helps a lot indeed, thank you very much.

**Comment by Hakky54** [comment]
Yes the client application.yml file is contains custom properties and mostly not related to spring at all. So spring won't pick it up. It was just a convenient way to adjust properties and enable custom configuration within a bean to showcase different scenario's for for this tutorial.

Great to hear that this repo helped you! By the way as you are not using openssl, this keytool cheatsheet might be usefull to bookmark: https://gist.github.com/Hakky54/7a2f0fcbcf5fdf4674d48f1a0b31c862 
I made this cheatsheet based on the tutorial of this repo.

I am closing this issue as it seems like there is no issue anymore on your side, right? Or do you need help with something?

**Comment by Roan123** [comment]
no issue anymore, thanks again!
