### ISSUE TITLE
class path resource [identity.jks] cannot be resolved to URL because it does not exist

### ISSUE THREAD

**Issue by naptoon** [Hakky54/mutual-tls-ssl#103]
**Describe the bug**
When I add the key-store etc. settings to application.yaml and try to restart the server, I get an error:
"java.io.FileNotFoundException: class path resource [identity.jks] cannot be resolved to URL because it does not exist".
The file exists within shared-server-resources.src.main.resources.

**To Reproduce**
I followed the readme instructions. No code changes except the ssl settings in application.yaml.

**Expected behavior**
The server should start properly.

**Environmental Data:**
 - Java Version 19.0.2
 - Maven Version 3.9.6
- MacOS 14.4.1

**Comment by Hakky54** [comment]
This can happen when the `shared-server-resources` is not build before. I would recommend to run first `mvn clean install -pl shared-server-resources` and then restart the server. Can you give it a try on your side?

**Comment by naptoon** [comment]
Yes, this helped. Thank you!

**Comment by Hakky54** [comment]
Awesome, good luck following all the steps. Feel free to open new issues if you gave something else

**Comment by naptoon** [comment]
Just a question: how would the client setting be when we have two different
servers and one client?

Hakan Altındağ ***@***.***> schrieb am Di. 7. Mai 2024 um
10:22:

**Comment by Hakky54** [comment]
If you have two servers with mutual authentication you can just add the client cert to both of the server truststores and add both server certificates to the client truststore. This should work anf if it does not work you need to add a client identity route, see also here: [Routing identity material to specific host
](https://github.com/Hakky54/sslcontext-kickstart?tab=readme-ov-file#routing-identity-material-to-specific-host)
