### ISSUE TITLE
Asking help about the No Subject Alternative Name 

### ISSUE THREAD

**Issue by darapenhchet** [Hakky54/mutual-tls-ssl#29]
Dear Mr/Mrs,

Could I ask you about the No Subjet Alternative Name with WebClientNetty?

Best Regards,
Dara Penhchet

**Comment by Hakky54** [comment]
Hi @darapenhchet 

Sure, what is your question?

**Comment by darapenhchet** [comment]
Dear sir,

I have followed your code with WebClientNetty and it shows the error. Your Certificate no subject alternative Name, but my certificate included that SAN already. Have you ever met those errors?

Best Regards
Dara Penhchet

**Comment by Hakky54** [comment]
I encountered a similar exception as mentioned at this stackoverflow question: https://stackoverflow.com/questions/50928061/certificate-for-localhost-doesnt-match-any-of-the-subject-alternative-names/53822999#53822999

Are you getting the same exception as mentioned at the stackoverflow question? Could you share your specific exception and also the stacktrace here?
And could you also share the exact command for creating the keystore with keypair for the server?

Could you also share your application.yml file of the server?

**Comment by Hakky54** [comment]
Closing issue because not getting a response after two weeks
