### ISSUE TITLE
Asking help about the check the Certificate Status with OCSP with TLS Connection?

### ISSUE THREAD

**Issue by darapenhchet** [Hakky54/mutual-tls-ssl#34]
Dear Mr/Mrs ,

Could I ask you about how to check the Certificate Status with OCSP Responder with TLS Connection?

Best Regards,
Dara Penhchet

**Comment by Hakky54** [comment]
Hi,

I found two good examples which demonstrates how to do it at github, see:
- https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/share/classes/sun/security/provider/certpath/OCSP.java
- https://github.com/wdawson/revoker

What you need to do is grab the crl or ocsp url within the certificate chain and validate it.
If we look at the certificate of github itself, these urls are present for both crl and ocsp.

<img width="486" alt="Screenshot 2020-01-01 at 19 48 18" src="https://user-images.githubusercontent.com/16032204/71644886-095b0080-2cd0-11ea-9c69-c4e52c779a3c.png">
<img width="486" alt="Screenshot 2020-01-01 at 19 48 09" src="https://user-images.githubusercontent.com/16032204/71644887-095b0080-2cd0-11ea-9b00-35be44ed510a.png">

I will try to include an example within this projects for this usecasse, but it wont be within a month or two..
