### ISSUE TITLE
A request for examples using standard servers with JAX-RS instead of SpringBoot

### ISSUE THREAD

**Issue by stdunbar** [Hakky54/mutual-tls-ssl#70]
**Describe the solution you'd like**
I'd like to see how to deploy this to standard servers with JAX-RS rather than a SpringBoot environment.  The current code is challenging to use in a traditional Tomcat/Wildfly/etc. type of environment.

**Comment by Hakky54** [comment]
Hi @stdunbar thank you for stopping by and asking for an example. I am not able to fully understand your request. Would you like to have a plain Jax rs server implementation with tomcat and a wildly server example?
