### ISSUE TITLE
Build with mvn is not working

### ISSUE THREAD

**Issue by hisashiyamaguchi** [Hakky54/mutual-tls-ssl#83]
**Describe the bug**

I'm trying to build with mvn, but it's not working. You can find the output here.
https://gist.github.com/hisashiyamaguchi/7e8ffc6ae8f0db78cd55456078b63204

**To Reproduce**
1. Provide as much of a code sample as possible.
cd server-with-spring-boot/ && mvn spring-boot:run
2. provide full stack traces if possible

**Expected behavior**

**Screenshots**

**Environmental Data:**
 - Java Version
 java version "1.7.0_261"
OpenJDK Runtime Environment (rhel-2.6.22.2.amzn2.0.1-x86_64 u261-b02)
OpenJDK 64-Bit Server VM (build 24.261-b02, mixed mode)

 - Maven Version
Maven home: /usr/share/apache-maven
Java version: 1.7.0_261, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.261-2.6.22.2.amzn2.0.1.x86_64/jre
Default locale: ja_JP, platform encoding: UTF-8
OS name: "linux", version: "4.14.214-160.339.amzn2.x86_64", arch: "amd64", family: "unix"

- OS (Windows/Linux/MacOS)
Linux ip-172-31-18-187.us-east-2.compute.internal 4.14.214-160.339.amzn2.x86_64 #1 SMP Sun Jan 10 05:53:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by Hakky54** [comment]
Hi @hisashiyamaguchi 

The server project depends on another maven submodule and the stacktrace is saying that it cannot find that artifact. What you need to do is first run `mvn clean install` within the root directory.

I also see that you are using java 7, but the documentation mentions to use java 11. That will also resolve other upcoming errors.

Can you retry and share your results here?

**Comment by hisashiyamaguchi** [comment]
Thanks for the quick and detailed follow-up - it seemed that JAVA_HONE was not configured properly. After putting the 2lines on my .bashrc here, it works!

export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto.x86_64
export PATH=$JAVA_HOME/bin:$PATH
