### ISSUE TITLE
Enable Client Cert validation only for a single end point at Service end (Spring Boot Java)?

### ISSUE THREAD

**Issue by sivareddyforu** [Hakky54/mutual-tls-ssl#86]
**Is your feature request related to a problem? Please describe.**
I would like to learn on how to enable the client cert validation only on a certain end point, say i would like to enable S2S authentication through a /token end point and this end point alone validates the Client Cert and subsequent requests will carry the token generated by this end point? How to do this at Service end?

**Describe the solution you'd like**
I would like to learn on how to enable the client cert validation only on a certain end point, say i would like to enable S2S authentication through a /token end point and this end point alone validates the Client Cert and subsequent requests will carry the token generated by this end point? How to do this at Service end?

**Describe alternatives you've considered**
Also, In your Spring Boot example, I could not see how the Client Cert is validated other than loading the cert and validating common name?

**Additional context**
NA

**Comment by Hakky54** [comment]
Hi Siva

I am not 100% sure if this is possible as I have never tried it before. But what I know is that spring boot is using tomcat by default under the covers which is able to have multiple connectors. So what you can do have two connectors. One for http and one for https. I think this is the only way, but I am not sure. When your server is running only https it is not possible to disable ssl or else it needs to be running under http.

You might want to read these topics as I have found it very useful:
- [Spring Boot: Disable Client Auth for specific URL](https://stackoverflow.com/questions/48116984/spring-boot-disable-client-auth-for-specific-url)
- [How set up Spring Boot to run HTTPS / HTTP ports](https://stackoverflow.com/questions/30896234/how-set-up-spring-boot-to-run-https-http-ports)

The second link is already giving an example implementation. I think the remaining part is to route the correct endpoint to the correct connector.

> Also, In your Spring Boot example, I could not see how the Client Cert is validated other than loading the cert and validating common name?
The common name validator is a custom validation based on aspect oriented programming with assertj. I intercepted the https call to just validate the common name.

Regarding your question of client authentication. It will get enabled by passing on the property `client-auth: need` See below for the screenshot. Spring will pass this property on to Tomcat and Tomcat will do the client authentication somewhere in the chain. To be exactly here: `sun.security.ssl.SSLEngineImpl` and `sun.security.ssl.X509TrustManagerImpl`. You can see that by your self by just adding breakpoints and running the server on debug mode.

![Screenshot 2021-05-18 at 15 47 15](https://user-images.githubusercontent.com/16032204/118662485-5457b400-b7f0-11eb-8946-521ec4b27364.png)

**Comment by sivareddyforu** [comment]
Thanks @Hakky54 for the detailed info. I am quite new to this area and you have given some valuable information.
I will dig in more. What I see another better way could be to create a parallel identity service which would validate the client cert (This way Client is forced to use a valid Client Cert for pre auth) and generate an access token based on the successful validation and communicate back to client for further communication with your other functional backend services (The other functional backend services can internally validate the Client access token with original Identity service allow for further processing securely). My main idea was to restrict the Client Cert validation on every communication with Client Service to Server Service to avoid performance bottlenecks, however am totally unaware what is the best practice here.

**Comment by Hakky54** [comment]
> My main idea was to restrict the Client Cert validation on every communication with Client Service to Server Service there by avoiding any performance bottlenecks, however am totally unaware what is the best practice here.

Well I understand your use case and the alternative solution and I think it is a very good to have this concern to help you improve your application performance. Although the ssl handshake is using very minimum time it is still using some time, in my opinion it is ignorable because in my use case it was less than 1ms. However what you can try out is to increase the ssl session timeout, in that way a client does not need to redo the ssl handshake if the server still has cached it and the main benefit is that https is still present.

If you are using my library this can be easily configured, see here for the details: [Managing ssl session](https://github.com/Hakky54/sslcontext-kickstart#managing-ssl-session)
```
SSLFactory sslFactory = SSLFactory.builder()
          .withIdentityMaterial("identity.jks", "password".toCharArray())
          .withTrustMaterial("truststore.jks", "password".toCharArray())
          .withNeedClientAuthentication()
          .withSessionTimeout(60 * 60 * 24) // Amount of seconds until it will be invalidated. 60 * 60 * 24 results into 1 hour
          .withSessionCacheSize(1024) // Amount of bytes until it will be invalidated
          .build();
```

**Comment by Hakky54** [comment]
Hey @sivareddyforu any news from your side? Did you tried with increased session timout?

**Comment by Hakky54** [comment]
Sure, please drop any comment here. I would love to hear the status of it. Good luck!
