### ISSUE TITLE
All client tests fail, potential regression from a dependency

### ISSUE THREAD

**Issue by nikola-shekerev** [Hakky54/mutual-tls-ssl#87]
Greetings, dear human. Good project, have my star

**Describe the bug**
I believe a dependency of the client broke it, causing a regression. Specifically how the client finds its truststore

**To Reproduce**
- I start a fresh Ubuntu 18 VM. I install requirements - Java 11 and JAVA_HOME properly, maven, clone the repo. My point is that I have double-checked the issue below occurs on a fresh machine.
- I run "mvn install" from project root. All green
- I run server in "server-with-spring-boot" and I run client tests. All green
- I run script "configure-one-way-authentication" successfully. I check manually that the correct artifacts are created  properly. I do tried doing this step manually. My point is that the issue below occurs regardless if I do the changes manually or if I use the script in the repo
- Side note - for server keystore and server truststore I use folder "server-with-spring-boot" instead of folder "shared-server-resources" . I do this, because if I follow the readme as is, the server does not start because it cannot find its keystore. This is not the reason for this ticket but a side note with a viable workaround.
- I run the server in "server-with-spring-boot" and it starts successfully.
- I run the following test with curl and it tells me the server behaves as expected
"curl -i --insecure -v -XGET https://localhost:8443/api/hello"
- I run client tests. All fail with "PKIX path building failed" error, the same error mentioned in the readme, suggesting the client still cannot find its truststore. I double check the client trust store is where it is expected to be and the server fingerprint is the server fingerprint. The issue is not in the truststore.
- A friend used this project 2 weeks ago and confirmed this issue was not present back then. This friend used Ubuntu 18 as well. I checked the code changes since then and I do not see anything that could have caused described behavior. I repeated the process described here with a commit hash from 2 weeks ago and the issue still occurs
- If I setup 2-way tls, client still does not find its truststore
- All the above suggests that a dependency broke the client. It does not look like author code changes caused the issue

**Comment by Hakky54** [comment]
Hi Nikola,

Thank you for trying out this project and sharing your issues. So it looks like the server is not able to find the certificates although you see that everything is present. I think the server is not able to find it as it may not be present at the classpath, but this is an assumption... Do you start the server through Maven or through your Intellij IDEA/Eclipse?

If you do start the server through maven you can try to run `mvn package` first to make sure the server can load the files from the classpath. Can you retry and share your results?

**Comment by nikola-shekerev** [comment]
Greetings

I believe the issue is with client, not with server

I ran `mvn package` in client folder and I got this error just now
```
[ERROR] Failures: 
[ERROR]   ClientConfigShould.createCxfWebClientWithSecurity:341 
Expecting a throwable with root cause being an instance of:
  java.net.ConnectException
but was an instance of:
  sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  ```

**Comment by Hakky54** [comment]
Hmm, thats strange. I did the exact same thing on my side and not getting the same issue. I would like to replicate the same behaviour as what you got. 

So your environment is Ubuntu 18. Which java and maven are you using? Can you share the result of `mvn -v` and `java -version`

**Comment by nikola-shekerev** [comment]
```
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

javac -version
javac 11.0.11

echo $JAVA_HOME
/usr/lib/jvm/java-11-openjdk-amd64

mvn -v
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-80-generic", arch: "amd64", family: "unix"
```

Items were installed with the following commands
```
sudo apt install default-jre
sudo apt install default-jdk
sudo apt install maven
```

Maven is 3.6 instead of the requested 3.5 in readme, but the friend I mentioned in original post used the same and did not have this issue, so I ruled it out as the cause. I got my Ubunto disk from him, so I also ruled out the OS version as the cause.

**Comment by Hakky54** [comment]
I have prepared the same setup as you mentioned and in my case only 2 http clients failed (Apache CXF based).
I have pushed the fix to the master branch. In your case all of the http clients failed, that didn't happen on my side. So I am not sure what the cause is although the Ubuntu, Java and Maven versions are the same.

So what I did was:
1. Clone the project
2. Run the script: `./script/configure-one-way-authentication.sh`
3. Rebuild project: `mvn clean install`
4. cd to server and start it: `cd server-with-spring-boot/ && nohup mvn spring-boot:run`
5. cd to client and start it: `cd client/ && java -jar target/client.jar`

Can you retry with the latest commit? If it still not works we can do a remote pair-programming session and in that way I can analyse your issue more in dept.

**Comment by nikola-shekerev** [comment]
On my side the server does not start with `nohup mvn spring-boot:run &`

I start it with `sudo mvn spring-boot:run &` instead.

Your fix worked and the tests pass

**Comment by Hakky54** [comment]
Awesome, really glad to hear it worked! Thank you again for pointing out the issue, thanks to you the project is more solid! 🎉
