### ISSUE TITLE
Invalid Keystore Format

### ISSUE THREAD

**Issue by karanvelayudham** [Hakky54/mutual-tls-ssl#94]
Followed all the steps mentioned in the README to start the server, But getting Invalid keystore format error while running application. Screenshot and logs attached. Please help me setup mtls server. 
![image](https://user-images.githubusercontent.com/89380182/158129319-4e2723a0-e58f-4634-ac44-0a171dc4b709.png)
![image](https://user-images.githubusercontent.com/89380182/158129335-49c4d6ee-d516-4137-bfc5-2122f129135e.png)
[mtlsError.txt](https://github.com/Hakky54/mutual-tls-ssl/files/8242838/mtlsError.txt)

**Comment by Hakky54** [comment]
Hi @karanvelayudham 

Can you share some more details regarding your setup? Which OS and JDK are you using? How do you start the server?

**Comment by karanvelayudham** [comment]
i am using windows and jdk 11. i followed your readme instructions to start server, it was running without encryption, i I had generated the certificate and When i try to enable one way TLS  , i am getting this error

**Comment by Hakky54** [comment]
Yess, clear and which JDK are you using, zulu, oracle or some other?

**Comment by karanvelayudham** [comment]
Oracle JDK 11

**Comment by Hakky54** [comment]
That is strange. I have it also locally and it is working fine. Do you have some time today or tomorrow to have a call so I can look at your setup and we can walk through it together?

**Comment by karanvelayudham** [comment]
Appreciate your help man! But I can't have a external call and share screen from this machine since it is in my organizations network.
Thank you

**Comment by Hakky54** [comment]
I can understand that, sure no worries.

So what I can recommend is to go through this video walkthrough: https://github.com/Hakky54/mutual-tls-ssl#demo-and-walk-through-video

If that is still not working you could add the snippet below to the following file locally: https://github.com/Hakky54/mutual-tls-ssl/blob/master/shared-server-resources/pom.xml Maven might be corrupting the data while packaging, see here for more: https://stackoverflow.com/questions/1052700/java-io-ioexception-invalid-keystore-format
```xml
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>identity.jks</include>
                    <include>truststore.jks</include>
                </includes>
                <filtering>false</filtering>
            </resource>
        </resources>
    </build>
```

A last resort is to run this project in gitpod which is an isolated environment setup with couple of tools such as java, maven and visual studio code which already has proven to work over there.

I am not sure why it is not working on your machine as I have run it multiple times also on windows with oracle jdk. Can you try the options above and share your progress?

**Comment by karanvelayudham** [comment]
this snippet did worked! Thanks @Hakky54 .
I am able to run application now.

**Comment by Hakky54** [comment]
Awesome to hear! By the way I noticed that the Scala compiler was failing on Windows, so I have fixed that yesterday. If you pull the latest version of the master your build will be running more smoothly. I am closing this issue. IF you have any other issues or questions feel free to open a new issue!

**Comment by Hakky54** [comment]
By the way @karanvelayudham So which snippet did do the trick for you?

**Comment by karanvelayudham** [comment]
Build snippet that you shared above, i added in pom and did mvn clean install
